server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aiactions_db
    username: aiactions_user
    password: jang4360
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update 또는 create 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # 초기 sql 삽입을 원할 경우

